const JobApplication = require("../models/JobApplication.js");
const ResumeProfile = require("../models/ResumeProfile.js");
const JobPreference = require("../models/JobPreference.js");

const normalized = (value) => String(value || '').toLowerCase();
const list = (value) => Array.isArray(value) ? value : [];
const overlapScore = (required, available) => { const source = list(available).map(normalized); const wanted = list(required).map(normalized); if (!wanted.length) return 100; return Math.round((wanted.filter((item) => source.some((candidate) => candidate.includes(item) || item.includes(candidate))).length / wanted.length) * 100); };
const matchJob = (job, profile, preference) => { const skills = [...new Set([...list(profile?.skills), ...list(profile?.technicalSkills), ...list(preference?.skills), ...list(preference?.technologies)])]; const skillsMatch = overlapScore([...(job.requiredSkills || []), ...(job.preferredSkills || [])], skills); const roleMatch = list(preference?.preferredJobTitles).length ? overlapScore(preference.preferredJobTitles, [job.jobTitle]) : 100; const locationMatch = list(preference?.preferredLocations).length ? overlapScore(preference.preferredLocations, [job.location]) : 100; const experienceMatch = preference?.maximumExperienceRequired == null || profile?.experienceYears == null ? 100 : profile.experienceYears <= preference.maximumExperienceRequired ? 100 : 50; const salaryMatch = 100; const matchScore = Math.round(skillsMatch * 0.35 + roleMatch * 0.25 + locationMatch * 0.2 + experienceMatch * 0.1 + salaryMatch * 0.1); const recommendation = matchScore >= (preference?.minimumMatchScore ?? 75) ? 'APPLY' : 'REVIEW'; return { matchScore, skillsMatch, roleMatch, locationMatch, experienceMatch, salaryMatch, recommendation, explanation: { matchedSkills: (job.requiredSkills || []).filter((skill) => skills.some((item) => normalized(item).includes(normalized(skill)))), potentialGaps: (job.requiredSkills || []).filter((skill) => !skills.some((item) => normalized(item).includes(normalized(skill)))) } }; };
const eligibility = async (job, adminId, match) => { const [preference, profile, existing, today] = await Promise.all([JobPreference.findOne({ admin: adminId }), ResumeProfile.findOne({ admin: adminId }), JobApplication.findOne({ companyName: job.companyName, jobTitle: job.jobTitle, admin: adminId }), JobApplication.countDocuments({ admin: adminId, applicationDate: { $gte: new Date(new Date().setHours(0, 0, 0, 0)) } })]); const excluded = list(preference?.excludeCompanies).some((name) => normalized(name) === normalized(job.companyName)); const includedOnly = list(preference?.includeCompanies).length && !preference.includeCompanies.some((name) => normalized(name) === normalized(job.companyName)); const eligible = Boolean(match.recommendation === 'APPLY' && !excluded && !includedOnly && !existing && today < (preference?.dailyApplicationLimit ?? 10) && profile); return { eligible, reasons: [...(excluded ? ['Company is excluded'] : []), ...(includedOnly ? ['Company is not on the include list'] : []), ...(existing ? ['Application already exists'] : []), ...(today >= (preference?.dailyApplicationLimit ?? 10) ? ['Daily application limit reached'] : []), ...(!profile ? ['Verified resume profile is missing'] : [])], applicationsToday: today, remainingToday: Math.max(0, (preference?.dailyApplicationLimit ?? 10) - today) }; };
module.exports = { matchJob, eligibility };
