const mongoose = require("mongoose");

const STATUS_VALUES = ["Discovered", "Matched", "Ready to Apply", "Applied", "Application Received", "Under Review", "Assessment", "Interview", "Interview Scheduled", "Interview Completed", "HR Round", "Offer", "Offer Received", "Selected", "Rejected", "Withdrawn", "Failed", "Needs Review", "Unknown"];
const timelineSchema = new mongoose.Schema({ event: { type: String, default: "Status updated" }, status: { type: String, enum: STATUS_VALUES }, date: { type: Date, default: Date.now }, sourceEmail: { type: String, default: "" }, gmailMessageId: { type: String, default: "" }, extractedInformation: { type: mongoose.Schema.Types.Mixed, default: {} } }, { _id: true });
const questionSchema = new mongoose.Schema({ question: { type: String, required: true }, answer: { type: String, default: "" }, source: { type: String, enum: ["verified", "resume", "manual", "unknown"], default: "unknown" }, requiresHumanReview: { type: Boolean, default: false } }, { _id: false });

const jobApplicationSchema = new mongoose.Schema({
  admin: { type: mongoose.Schema.Types.ObjectId, ref: "Admin", required: true, index: true },
  companyName: { type: String, trim: true, required: true }, jobTitle: { type: String, trim: true, required: true }, jobUrl: { type: String, trim: true, default: "" }, applicationUrl: { type: String, trim: true, default: "" }, location: { type: String, trim: true, default: "" }, salary: { type: String, trim: true, default: "" }, employmentType: { type: String, trim: true, default: "" }, jobDescription: { type: String, default: "" }, requiredSkills: { type: [String], default: [] }, preferredSkills: { type: [String], default: [] }, matchScore: { type: Number, min: 0, max: 100, default: 0 }, skillsMatch: { type: Number, min: 0, max: 100, default: 0 }, experienceMatch: { type: Number, min: 0, max: 100, default: 0 }, locationMatch: { type: Number, min: 0, max: 100, default: 0 }, roleMatch: { type: Number, min: 0, max: 100, default: 0 }, salaryMatch: { type: Number, min: 0, max: 100, default: 0 }, recommendation: { type: String, enum: ["APPLY", "REVIEW", "SKIP", "UNKNOWN"], default: "UNKNOWN" }, status: { type: String, enum: STATUS_VALUES, default: "Unknown" }, source: { type: String, default: "Manual" }, postedDate: { type: Date }, applicationDate: { type: Date }, resumeId: { type: mongoose.Schema.Types.ObjectId, ref: "ResumeProfile" }, recruiterName: { type: String, trim: true, default: "" }, recruiterEmail: { type: String, trim: true, lowercase: true, default: "" }, interviewDate: { type: Date }, confidence: { type: Number, min: 0, max: 1, default: 1 }, isVerified: { type: Boolean, default: false }, needsReview: { type: Boolean, default: false }, automationMode: { type: String, enum: ["review", "assisted", "full"], default: "review" }, submissionStatus: { type: String, enum: ["not-started", "preparing", "ready", "submitted", "needs-review", "failed", "manual"], default: "not-started" }, failureReason: { type: String, default: "" }, applicationQuestions: { type: [questionSchema], default: [] }, applicationAnswers: { type: mongoose.Schema.Types.Mixed, default: {} }, timeline: { type: [timelineSchema], default: [] }, gmailMessageIds: { type: [String], default: [] }, gmailThreadId: { type: String, default: "" }, lastSourceEmail: { type: String, default: "" }, lastEmailSubject: { type: String, default: "" }, isFavorite: { type: Boolean, default: false }, eligibility: { type: mongoose.Schema.Types.Mixed, default: {} }, queuePosition: { type: Number }, attemptCount: { type: Number, default: 0 }, lastAttemptAt: { type: Date }, processedAt: { type: Date }, notes: { type: String, default: "" },
}, { timestamps: true, versionKey: false });

jobApplicationSchema.index({ companyName: 1, jobTitle: 1, recruiterEmail: 1 });
jobApplicationSchema.index({ gmailMessageIds: 1 }, { sparse: true });
jobApplicationSchema.index({ status: 1, matchScore: -1, createdAt: -1 });
jobApplicationSchema.statics.statusValues = STATUS_VALUES;
module.exports = mongoose.model("JobApplication", jobApplicationSchema);
